git:
    depth: 1

cache:
    directories:
        - $HOME/.composer

sudo: false

language: php

notifications:
    email: false

before_install:
    - composer self-update --stable
    - composer global show hirak/prestissimo -q || composer global require hirak/prestissimo

install:
    - composer install

script:
    - vendor/bin/phpcs --exclude=Generic.Files.LineLength --report-full --standard=PSR2 src tests
    - vendor/bin/php-cs-fixer fix --config=tests/php-cs-fixer.config.php --diff --dry-run
    - vendor/bin/types-checker src tests
    - vendor/bin/psalm --config=tests/psalm.xml
    - phpdbg -qrr vendor/bin/phpunit --configuration=tests

jobs:
    include:
        - &STANDARD_TEST_JOB
            stage: Test
            php: '7.1'
            install: composer update --prefer-lowest
        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: '7.1'
        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: '7.2'
        -
            <<: *STANDARD_TEST_JOB
            stage: Test
            php: '7.2'
            install: composer require --dev php-coveralls/php-coveralls
            script: phpdbg -qrr vendor/bin/phpunit --configuration=tests --coverage-clover=build/logs/clover.xml
            after_success: vendor/bin/php-coveralls

        -
            stage: Verify correctness for PHP CS Fixer
            php: '7.2'
            install: ~
            before_script:
                - phpenv config-rm xdebug.ini || return 0
            script:
                # prepare PHP CS Fixer
                - composer create-project --no-interaction --prefer-source friendsofphp/php-cs-fixer tmp
                # prepare fixers
                - mkdir tmp/src/Fixer/CustomFixers
                - cp src/Fixer/* tmp/src/Fixer/CustomFixers
                - rm tmp/src/Fixer/CustomFixers/AbstractFixer.php
                - sed -i -- 's/namespace PhpCsFixerCustomFixers\\Fixer;/namespace PhpCsFixer\\Fixer\\CustomFixers;use PhpCsFixer\\AbstractFixer;use PhpCsFixer\\Preg;/g' tmp/src/Fixer/CustomFixers/*
                - sed -i -- 's/use PhpCsFixerCustomFixers\\CommentRemover;/use PhpCsFixer\\CommentRemover;/g' tmp/src/Fixer/CustomFixers/*
                - sed -i -- 's/public function fix/protected function applyFix/g' tmp/src/Fixer/CustomFixers/*
                - sed -i -- 's/\\preg_/Preg::/g' tmp/src/Fixer/CustomFixers/*
                - sed -i -- 's/Preg::quote/preg_quote/g' tmp/src/Fixer/CustomFixers/*
                - cp src/CommentRemover.php tmp/src/CommentRemover.php
                - sed -i -- 's/namespace PhpCsFixerCustomFixers;/namespace PhpCsFixer;use PhpCsFixer\\Preg;/g' tmp/src/CommentRemover.php
                - sed -i -- 's/\\preg_/Preg::/g' tmp/src/CommentRemover.php
                - sed -i -- 's/Preg::quote/preg_quote/g' tmp/src/CommentRemover.php
                # prepare tests
                - mkdir tmp/tests/Fixer/CustomFixers
                - cp tests/Fixer/* tmp/tests/Fixer/CustomFixers
                - rm tmp/tests/Fixer/CustomFixers/AbstractFixerTestCase.php
                - sed -i -- 's/namespace Tests\\Fixer;/namespace PhpCsFixer\\Tests\\Fixer\\CustomFixers;use PhpCsFixer\\Tests\\Test\\AbstractFixerTestCase;/g' tmp/tests/Fixer/CustomFixers/*
                - sed -i -- 's/PhpCsFixerCustomFixers\\Fixer/PhpCsFixer\\Fixer\\CustomFixers/g' tmp/tests/Fixer/CustomFixers/*
                - cp tests/CommentRemoverTest.php tmp/tests/CommentRemoverTest.php
                - sed -i -- 's/namespace Tests;/namespace PhpCsFixer\\Tests;/g' tmp/tests/CommentRemoverTest.php
                - sed -i -- 's/use PhpCsFixerCustomFixers\\CommentRemover;/use PhpCsFixer\\CommentRemover;/g' tmp/tests/CommentRemoverTest.php
                - sed -i -- 's/use PHPUnit\\Framework\\TestCase;/use PhpCsFixer\\Tests\\TestCase;/g' tmp/tests/CommentRemoverTest.php
                - sed -i -- 's/@covers \\PhpCsFixerCustomFixers/@covers \\PhpCsFixer/g' tmp/tests/CommentRemoverTest.php
                # prepare for testing
                - cd tmp
                - php php-cs-fixer fix src/Fixer/CustomFixers
                - php php-cs-fixer fix tests/Fixer/CustomFixers
                - php php-cs-fixer readme > README.rst
                # test
                - vendor/bin/phpunit
